<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $properties = [
            [
                'name' => 'Kosan Putri Mawar Indah',
                'slug' => Str::slug('Kosan Putri Mawar Indah'),
                'address' => 'Jl. Melati No. 12, Sleman, Yogyakarta',
                'category' => 'kosan',
                'description' => 'Kosan eksklusif untuk putri, lokasi strategis dekat kampus UGM dan UNY.',
                'land_area' => 120,
                'type' => null,
                'price' => 1500000,
                'facilities' => ['WiFi', 'AC', 'Kamar mandi dalam', 'Dapur bersama', 'Parkir motor'],
                'remaining_units' => 3,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putra Griya Bahagia',
                'slug' => Str::slug('Kosan Putra Griya Bahagia'),
                'address' => 'Jl. Kaliurang Km 5, Sleman, Yogyakarta',
                'category' => 'kosan',
                'description' => 'Kosan nyaman untuk mahasiswa, dekat kampus dan area kuliner.',
                'land_area' => 150,
                'type' => null,
                'price' => 1300000,
                'facilities' => ['WiFi', 'Kamar mandi dalam', 'Parkir motor', 'Dapur umum'],
                'remaining_units' => 5,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Afaris Residence Condong Catur',
                'slug' => Str::slug('Afaris Residence Condong Catur'),
                'address' => 'Jl. Anggrek No. 9, Condong Catur, Sleman',
                'category' => 'residence',
                'description' => 'Hunian modern dengan fasilitas lengkap dan keamanan 24 jam.',
                'land_area' => 300,
                'type' => 2,
                'price' => 250000000,
                'facilities' => ['Kolam renang', 'Keamanan 24 jam', 'Garasi', 'Taman', 'AC'],
                'remaining_units' => 2,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putri Melati Asri',
                'slug' => Str::slug('Kosan Putri Melati Asri'),
                'address' => 'Jl. Cendana No. 5, Depok, Sleman',
                'category' => 'kosan',
                'description' => 'Kosan khusus putri dengan suasana tenang dan nyaman.',
                'land_area' => 100,
                'type' => null,
                'price' => 1200000,
                'facilities' => ['WiFi', 'Kamar mandi dalam', 'Laundry', 'Parkir motor'],
                'remaining_units' => 4,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Griya Harmoni Residence',
                'slug' => Str::slug('Griya Harmoni Residence'),
                'address' => 'Jl. Kenanga No. 15, Bantul, Yogyakarta',
                'category' => 'residence',
                'description' => 'Rumah siap huni dengan desain minimalis dan lingkungan asri.',
                'land_area' => 250,
                'type' => 3,
                'price' => 325000000,
                'facilities' => ['Garasi', 'Taman', 'AC', 'Dapur modern', 'Carport'],
                'remaining_units' => 1,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putra Cendana',
                'slug' => Str::slug('Kosan Putra Cendana'),
                'address' => 'Jl. Cendana No. 21, Sleman, Yogyakarta',
                'category' => 'kosan',
                'description' => 'Kosan murah dan nyaman, cocok untuk mahasiswa dan pekerja.',
                'land_area' => 90,
                'type' => null,
                'price' => 1000000,
                'facilities' => ['WiFi', 'Parkir motor', 'Dapur bersama'],
                'remaining_units' => 6,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Afaris Residence Seturan',
                'slug' => Str::slug('Afaris Residence Seturan'),
                'address' => 'Jl. Seturan Raya No. 3, Sleman, Yogyakarta',
                'category' => 'residence',
                'description' => 'Hunian eksklusif dengan konsep modern dan lokasi strategis.',
                'land_area' => 280,
                'type' => 4,
                'price' => 450000000,
                'facilities' => ['Kolam renang', 'CCTV', 'Garasi', 'Taman', 'Air panas'],
                'remaining_units' => 1,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putri Dahlia',
                'slug' => Str::slug('Kosan Putri Dahlia'),
                'address' => 'Jl. Monjali No. 8, Sleman, Yogyakarta',
                'category' => 'kosan',
                'description' => 'Kosan bersih, aman, dan nyaman untuk mahasiswi.',
                'land_area' => 110,
                'type' => null,
                'price' => 1400000,
                'facilities' => ['WiFi', 'AC', 'Kamar mandi dalam', 'Laundry'],
                'remaining_units' => 2,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Afaris Garden Residence',
                'slug' => Str::slug('Afaris Garden Residence'),
                'address' => 'Jl. Lempongsari No. 17, Sleman, Yogyakarta',
                'category' => 'residence',
                'description' => 'Rumah modern dengan taman pribadi dan lingkungan nyaman.',
                'land_area' => 320,
                'type' => 4,
                'price' => 500000000,
                'facilities' => ['Garasi', 'Taman', 'AC', 'Ruang keluarga luas'],
                'remaining_units' => 1,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putra Wijaya',
                'slug' => Str::slug('Kosan Putra Wijaya'),
                'address' => 'Jl. Pogung Lor No. 22, Sleman, Yogyakarta',
                'category' => 'kosan',
                'description' => 'Kosan dengan fasilitas lengkap dan akses mudah ke kampus.',
                'land_area' => 130,
                'type' => null,
                'price' => 1600000,
                'facilities' => ['WiFi', 'AC', 'Parkir motor', 'Kamar mandi dalam'],
                'remaining_units' => 3,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putri Anggrek Asri',
                'slug' => Str::slug('Kosan Putri Anggrek Asri'),
                'address' => 'Jl. Anggrek No. 7, Depok, Sleman',
                'category' => 'kosan',
                'description' => 'Kosan eksklusif khusus putri dengan suasana tenang dan aman.',
                'land_area' => 110,
                'type' => null,
                'price' => 1350000,
                'facilities' => ['WiFi', 'Kamar mandi dalam', 'AC', 'Laundry', 'Parkir motor'],
                'remaining_units' => 4,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putra Arjuna',
                'slug' => Str::slug('Kosan Putra Arjuna'),
                'address' => 'Jl. Maguwoharjo No. 10, Sleman, Yogyakarta',
                'category' => 'kosan',
                'description' => 'Kosan nyaman dengan akses mudah ke jalan utama dan area kuliner.',
                'land_area' => 95,
                'type' => null,
                'price' => 1100000,
                'facilities' => ['WiFi', 'Dapur bersama', 'Parkir motor', 'Laundry'],
                'remaining_units' => 5,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Afaris Residence Babarsari',
                'slug' => Str::slug('Afaris Residence Babarsari'),
                'address' => 'Jl. Babarsari No. 19, Sleman, Yogyakarta',
                'category' => 'residence',
                'description' => 'Hunian modern dekat area kampus dan pusat bisnis Babarsari.',
                'land_area' => 280,
                'type' => 2,
                'price' => 375000000,
                'facilities' => ['Garasi', 'AC', 'Taman', 'Dapur modern', 'Air panas'],
                'remaining_units' => 1,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Griya Permata Residence',
                'slug' => Str::slug('Griya Permata Residence'),
                'address' => 'Jl. Kaliurang Km 9, Sleman, Yogyakarta',
                'category' => 'residence',
                'description' => 'Rumah minimalis dengan lokasi strategis dan lingkungan nyaman.',
                'land_area' => 240,
                'type' => 3,
                'price' => 310000000,
                'facilities' => ['Garasi', 'Taman', 'Carport', 'Ruang keluarga luas'],
                'remaining_units' => 2,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putra Mawar Sejahtera',
                'slug' => Str::slug('Kosan Putra Mawar Sejahtera'),
                'address' => 'Jl. Mawar No. 5, Pogung, Sleman',
                'category' => 'kosan',
                'description' => 'Kosan strategis dekat UGM dengan harga terjangkau.',
                'land_area' => 100,
                'type' => null,
                'price' => 1250000,
                'facilities' => ['WiFi', 'Parkir motor', 'Kamar mandi dalam'],
                'remaining_units' => 3,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Afaris Elite Residence',
                'slug' => Str::slug('Afaris Elite Residence'),
                'address' => 'Jl. Palagan Tentara Pelajar No. 22, Sleman',
                'category' => 'residence',
                'description' => 'Perumahan mewah dengan konsep modern tropis.',
                'land_area' => 350,
                'type' => 4,
                'price' => 620000000,
                'facilities' => ['Kolam renang', 'Garasi', 'CCTV', 'Taman', 'Air panas'],
                'remaining_units' => 1,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putri Flamboyan',
                'slug' => Str::slug('Kosan Putri Flamboyan'),
                'address' => 'Jl. Flamboyan No. 8, Caturtunggal, Sleman',
                'category' => 'kosan',
                'description' => 'Kosan eksklusif dengan kamar ber-AC dan lokasi strategis.',
                'land_area' => 115,
                'type' => null,
                'price' => 1450000,
                'facilities' => ['WiFi', 'AC', 'Kamar mandi dalam', 'Laundry'],
                'remaining_units' => 2,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putra Merpati',
                'slug' => Str::slug('Kosan Putra Merpati'),
                'address' => 'Jl. Merpati No. 11, Sleman, Yogyakarta',
                'category' => 'kosan',
                'description' => 'Kosan bersih dan terawat dengan fasilitas lengkap.',
                'land_area' => 105,
                'type' => null,
                'price' => 1200000,
                'facilities' => ['WiFi', 'Parkir motor', 'Dapur bersama'],
                'remaining_units' => 4,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Griya Seturan Residence',
                'slug' => Str::slug('Griya Seturan Residence'),
                'address' => 'Jl. Seturan Tengah No. 20, Sleman, Yogyakarta',
                'category' => 'residence',
                'description' => 'Perumahan nyaman dengan konsep modern di pusat Seturan.',
                'land_area' => 260,
                'type' => 3,
                'price' => 390000000,
                'facilities' => ['Garasi', 'AC', 'Dapur modern', 'Taman'],
                'remaining_units' => 2,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putri Lavender',
                'slug' => Str::slug('Kosan Putri Lavender'),
                'address' => 'Jl. Lavender No. 6, Depok, Sleman',
                'category' => 'kosan',
                'description' => 'Kosan putri modern dengan desain interior elegan.',
                'land_area' => 100,
                'type' => null,
                'price' => 1600000,
                'facilities' => ['WiFi', 'AC', 'Laundry', 'Kamar mandi dalam'],
                'remaining_units' => 3,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Afaris Harmony Residence',
                'slug' => Str::slug('Afaris Harmony Residence'),
                'address' => 'Jl. Palagan No. 40, Sleman, Yogyakarta',
                'category' => 'residence',
                'description' => 'Hunian elegan dengan fasilitas premium di lingkungan tenang.',
                'land_area' => 340,
                'type' => 4,
                'price' => 575000000,
                'facilities' => ['Kolam renang', 'Garasi', 'AC', 'Taman', 'CCTV'],
                'remaining_units' => 1,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putra Sakura',
                'slug' => Str::slug('Kosan Putra Sakura'),
                'address' => 'Jl. Sakura No. 18, Pogung, Sleman',
                'category' => 'kosan',
                'description' => 'Kosan modern untuk mahasiswa dengan fasilitas lengkap.',
                'land_area' => 110,
                'type' => null,
                'price' => 1350000,
                'facilities' => ['WiFi', 'Kamar mandi dalam', 'Parkir motor', 'Laundry'],
                'remaining_units' => 5,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Griya Cempaka Residence',
                'slug' => Str::slug('Griya Cempaka Residence'),
                'address' => 'Jl. Cempaka No. 3, Bantul, Yogyakarta',
                'category' => 'residence',
                'description' => 'Perumahan minimalis di kawasan tenang dengan akses mudah ke kota.',
                'land_area' => 230,
                'type' => 3,
                'price' => 290000000,
                'facilities' => ['Garasi', 'Taman', 'Dapur modern'],
                'remaining_units' => 3,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putri Seruni',
                'slug' => Str::slug('Kosan Putri Seruni'),
                'address' => 'Jl. Seruni No. 2, Caturtunggal, Sleman',
                'category' => 'kosan',
                'description' => 'Kosan khusus putri dengan lingkungan aman dan bersih.',
                'land_area' => 90,
                'type' => null,
                'price' => 1200000,
                'facilities' => ['WiFi', 'Laundry', 'AC', 'Kamar mandi dalam'],
                'remaining_units' => 4,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Afaris Green Residence',
                'slug' => Str::slug('Afaris Green Residence'),
                'address' => 'Jl. Godean No. 17, Sleman, Yogyakarta',
                'category' => 'residence',
                'description' => 'Rumah dengan konsep eco-friendly dan lingkungan hijau.',
                'land_area' => 300,
                'type' => 4,
                'price' => 480000000,
                'facilities' => ['Garasi', 'Taman', 'Panel surya', 'AC', 'Air panas'],
                'remaining_units' => 1,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putra Kenari',
                'slug' => Str::slug('Kosan Putra Kenari'),
                'address' => 'Jl. Kenari No. 9, Sleman, Yogyakarta',
                'category' => 'kosan',
                'description' => 'Kosan ekonomis dengan fasilitas lengkap untuk mahasiswa.',
                'land_area' => 100,
                'type' => null,
                'price' => 1000000,
                'facilities' => ['WiFi', 'Parkir motor', 'Dapur bersama'],
                'remaining_units' => 6,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putri Jasmine',
                'slug' => Str::slug('Kosan Putri Jasmine'),
                'address' => 'Jl. Jasmine No. 15, Condong Catur, Sleman',
                'category' => 'kosan',
                'description' => 'Kosan eksklusif untuk mahasiswi dengan fasilitas modern.',
                'land_area' => 120,
                'type' => null,
                'price' => 1500000,
                'facilities' => ['WiFi', 'AC', 'Laundry', 'Kamar mandi dalam'],
                'remaining_units' => 3,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Griya Melati Residence',
                'slug' => Str::slug('Griya Melati Residence'),
                'address' => 'Jl. Melati No. 25, Bantul, Yogyakarta',
                'category' => 'residence',
                'description' => 'Hunian keluarga dengan desain minimalis dan asri.',
                'land_area' => 280,
                'type' => 3,
                'price' => 340000000,
                'facilities' => ['Garasi', 'Carport', 'Taman', 'Ruang keluarga'],
                'remaining_units' => 2,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Kosan Putra Cemara',
                'slug' => Str::slug('Kosan Putra Cemara'),
                'address' => 'Jl. Cemara No. 7, Pogung Kidul, Sleman',
                'category' => 'kosan',
                'description' => 'Kosan nyaman dan strategis, cocok untuk mahasiswa UGM.',
                'land_area' => 105,
                'type' => null,
                'price' => 1300000,
                'facilities' => ['WiFi', 'Parkir motor', 'Dapur bersama'],
                'remaining_units' => 4,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Afaris Premier Residence',
                'slug' => Str::slug('Afaris Premier Residence'),
                'address' => 'Jl. Kaliurang Km 7, Sleman, Yogyakarta',
                'category' => 'residence',
                'description' => 'Hunian eksklusif dengan konsep modern dan lokasi strategis.',
                'land_area' => 360,
                'type' => 4,
                'price' => 620000000,
                'facilities' => ['Kolam renang', 'CCTV', 'Garasi', 'Taman', 'Air panas'],
                'remaining_units' => 1,
                'status' => 'available',
                'featured_image' => null,
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
