<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $properties = [
            [
                'name' => 'Joeragan Kosan 1',
                'slug' => Str::slug('Joeragan Kosan 1'),
                'address' => 'Area Lingkar Kampus Darussalam (Blang Krueng)',
                'category' => 'kosan',
                'description' => 'Kosan eksklusif untuk putri, lokasi strategis dekat kampus UGM dan UNY.',
                'land_area' => 120,
                'type' => null,
                'price' => 1500000,
                'facilities' => ['WiFi', 'AC', 'Kamar mandi dalam', 'Dapur bersama', 'Parkir motor'],
                'remaining_units' => 3,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Kosan 2',
                'slug' => Str::slug('Joeragan Kosan 2'),
                'address' => 'Area Lingkar Kampus Darussalam (Blang Krueng)',
                'category' => 'kosan',
                'description' => 'Kosan nyaman untuk mahasiswa, dekat kampus dan area kuliner.',
                'land_area' => 150,
                'type' => null,
                'price' => 1300000,
                'facilities' => ['WiFi', 'Kamar mandi dalam', 'Parkir motor', 'Dapur umum'],
                'remaining_units' => 5,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Kosan 3',
                'slug' => Str::slug('Joeragan Kosan 3'),
                'address' => 'Area Strategis Kajhu (Dekat Pintu Tol Darussalam)',
                'category' => 'residence',
                'description' => 'Hunian modern dengan fasilitas lengkap dan keamanan 24 jam.',
                'land_area' => 300,
                'type' => 2,
                'price' => 250000000,
                'facilities' => ['Kolam renang', 'Keamanan 24 jam', 'Garasi', 'Taman', 'AC'],
                'remaining_units' => 2,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Kosan 4',
                'slug' => Str::slug('Joeragan Kosan 4'),
                'address' => 'Area Lingkar Kampus Darussalam (Blang Krueng)',
                'category' => 'kosan',
                'description' => 'Kosan khusus putri dengan suasana tenang dan nyaman.',
                'land_area' => 100,
                'type' => null,
                'price' => 1200000,
                'facilities' => ['WiFi', 'Kamar mandi dalam', 'Laundry', 'Parkir motor'],
                'remaining_units' => 4,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Kosan 5',
                'slug' => Str::slug('Joeragan Kosan 5'),
                'address' => 'Area Lingkar Kampus Darussalam (Blang Krueng)',
                'category' => 'residence',
                'description' => 'Rumah siap huni dengan desain minimalis dan lingkungan asri.',
                'land_area' => 250,
                'type' => 3,
                'price' => 325000000,
                'facilities' => ['Garasi', 'Taman', 'AC', 'Dapur modern', 'Carport'],
                'remaining_units' => 1,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 6',
                'slug' => Str::slug('Joeragan Residence 6'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng (Kota Banda Aceh)',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 7',
                'slug' => Str::slug('Joeragan Residence 7'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 8',
                'slug' => Str::slug('Joeragan Residence 8'),
                'address' => 'Area Ulee Kareng - Cot Cut, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 9',
                'slug' => Str::slug('Joeragan Residence 9'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 10',
                'slug' => Str::slug('Joeragan Residence 10'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 3,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 11',
                'slug' => Str::slug('Joeragan Residence 11'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 12',
                'slug' => Str::slug('Joeragan Residence 12'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 13',
                'slug' => Str::slug('Joeragan Residence 13'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 14',
                'slug' => Str::slug('Joeragan Residence 14'),
                'address' => 'Area Tungkop, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 15',
                'slug' => Str::slug('Joeragan Residence 15'),
                'address' => 'Area Lueng Bata - Pango, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 2,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 17',
                'slug' => Str::slug('Joeragan Residence 17'),
                'address' => 'Area Ulee Kareng - Cot Peutano, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 2,
                'status' => 'available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 18',
                'slug' => Str::slug('Joeragan Residence 18'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 19',
                'slug' => Str::slug('Joeragan Residence 19'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 0,
                'status' => 'not available',
                'featured_image' => null,
            ],
            [
                'name' => 'Joeragan Residence 20',
                'slug' => Str::slug('Joeragan Residence 20'),
                'address' => 'Area lingkar kampus di Darussalam - Blangkrueng, Kota Banda Aceh',
                'category' => 'residence',
                'description' => 'Kompleks hunian ini dirancang untuk memenuhi kebutuhan tempat tinggal yang nyaman dan fungsional di kawasan strategis Banda Aceh. Terletak di lingkungan yang tenang dan mudah diakses, setiap unit menawarkan tata ruang yang efisien serta fasilitas pendukung yang memadai. Lokasinya yang berdekatan dengan area kampus dan pusat aktivitas masyarakat menjadikannya pilihan ideal bagi mahasiswa, pekerja, maupun keluarga kecil yang mencari hunian praktis dengan akses mudah ke berbagai fasilitas umum.',
                'land_area' => 90,
                'type' => null,
                'price' => 230000000,
                'facilities' => ['Pagar Keliling Komplek', 'Jalan Rabat Beton', 'Listrik 6A', '2 Kamar Tidur', 'Ruang Tamu', '1 Area Dapur', 'Gratis : AC, Kitchen Set, Mesin Pompa Air, Fullset Teralis Jendela dan Lantai Granit'],
                'remaining_units' => 24,
                'status' => 'available',
                'featured_image' => null,
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
